# Generated by Django 2.2.5 on 2020-10-27 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('child_mode', models.BooleanField(default=False)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'events',
                'ordering': ['active'],
            },
        ),
    ]
