# Generated by Django 2.2.5 on 2020-10-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangorestapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('timer', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'quiz banks',
                'ordering': ['name'],
            },
        ),
    ]
