# Generated by Django 2.2.5 on 2020-10-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangorestapp', '0002_quizbank'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('image', models.URLField(blank=True, null=True)),
                ('value', models.IntegerField(default=1)),
                ('info_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Question Banks',
                'ordering': ['question'],
            },
        ),
    ]
