# Generated by Django 2.2.5 on 2020-10-28 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangorestapp', '0004_questionbankanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangorestapp.Event')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangorestapp.QuizBank')),
            ],
            options={
                'verbose_name_plural': 'Event Quizzes',
            },
        ),
    ]
