# Generated by Django 2.2.5 on 2020-10-28 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangorestapp', '0005_eventquiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangorestapp.QuestionBank')),
                ('quiz_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangorestapp.QuizBank')),
            ],
            options={
                'verbose_name_plural': 'quizzes questions',
            },
        ),
    ]
