# Generated by Django 2.2.5 on 2020-10-28 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangorestapp', '0007_auto_20201028_0111'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizTaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('fname', models.CharField(blank=True, max_length=255, null=True)),
                ('lname', models.CharField(blank=True, max_length=255, null=True)),
                ('score', models.IntegerField()),
                ('initials', models.CharField(max_length=3)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangorestapp.Event')),
                ('quiz_bank', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangorestapp.QuizBank')),
            ],
            options={
                'verbose_name_plural': 'quiz takers',
                'ordering': ['lname'],
            },
        ),
    ]
